// @ts-check
// Sidebar layout for the v2 docs site.
//
// Fully autogenerated from the docs/ folder tree:
//   - the root landing page (`intro`, sidebar_position 1, slug /) sorts first;
//   - each section is a top-level category whose order, label, link and
//     collapse state come from its `_category_.json`;
//   - each page inside a section orders by its `sidebar_position` front-matter.
//
// Section order is set by the `position` field in each `_category_.json`:
//   2 System architecture (the overview) · 3 Front-end · 4 Content architecture
//   · 5 Database · 6 Quiz management · 7 Deployment.
//
// Adding a page is a one-file operation: drop the .md into the section folder
// with a `sidebar_position`. No edit here is needed — the sidebar can never
// drift from what is on disk.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
