// @ts-check
// Sidebar layout for the Tenet docs site.
//
// Fully autogenerated from the docs/ folder tree:
//   - the root landing page (`intro`, sidebar_position 1, slug /) sorts first;
//   - each section is a top-level category whose order, label, link and
//     collapse state come from its `_category_.json`;
//   - each page inside a section orders by its `sidebar_position` front-matter.
//
// Three audience sections, ordered by the `position` field in each
// `_category_.json`:
//   2 User guide · 3 Admin guide · 4 Developer guide.
// The Developer guide nests sub-groups (architecture, components, data-model,
// quiz-internals) each with their own `_category_.json` position.
//
// Adding a page is a one-file operation: drop the .md into the section folder
// with a `sidebar_position`. No edit here is needed — the sidebar can never
// drift from what is on disk.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
