// Verbatim component instances extracted from the live monolith — the equivalence reference side.
// Auto-generated; do not hand-edit.
export const monolithRefs = {
  "scan-box": "<div class=\"scan-box\"><div class=\"scan-box-label\">30-second scan</div><ul>\n  <li><strong>What you will learn:</strong> How content moves from source to live page \u2014 through DAM ingestion, approval gates, localization pipelines, and sitemap registration \u2014 and where that journey breaks</li>\n  <li><strong>Why it matters:</strong> Broken content workflows are the single most common cause of go-live delays on enterprise builds; fixing them post-Sprint 5 costs three to five times what early modelling costs</li>\n  <li>Localization strategy is an architecture decision first \u2014 machine-translate-first and human-first require fundamentally different DAM folder structures, rendition naming conventions, and replication rules</li>\n  <li>The XML sitemap is a contract between SEO, Content, and Engineering \u2014 it defines what exists, what is indexable, and what the CMS must produce on every publish event</li>\n  <li>Content velocity is measurable: if an author needs more than 3 clicks to publish a page, the authoring model is wrong and throughput will be the constraint every release</li>\n</ul></div>",
  "callout-why": "<div class=\"callout callout-why\"><span class=\"callout-label\">Why This Matters</span><p>DAM folder taxonomy is an architecture decision, not a filing preference. The folder structure chosen in Discovery drives rendition paths, IAM permission groups, CDN cache-key patterns, and AEM replication rules. A brand-first hierarchy (<code>/brand/campaign/locale</code>) and a locale-first hierarchy (<code>/locale/brand/campaign</code>) produce entirely different CDN invalidation scopes and different asset-sharing rules across markets. Getting this wrong in week 2 costs weeks to unwind in Sprint 8 \u2014 after assets are referenced in hundreds of content fragments and replication agents are already configured.</p></div>",
  "callout-tip": "<div class=\"callout callout-tip\"><span class=\"callout-label\">Agency Tip</span><p>DEPT\u00ae field pattern: use a single <strong>Content Ready</strong> flag in Workfront or Jira that gates both legal sign-off and DAM final-rendition approval simultaneously. Two-track sign-off \u2014 legal marks approved while the DAM team is still processing final renditions, or vice versa \u2014 is the most common cause of last-minute go-live holds. One flag, two conditions, one gate. Make the flag unset-able only by a named release coordinator, not by either track independently. This eliminates the \"legal said yes but the image isn't in the DAM yet\" class of incident entirely.</p></div>",
  "callout-pitfall": "<div class=\"callout callout-pitfall\"><span class=\"callout-label\">Common Pitfall</span><p>Teams that skip approval workflow design before CMS configuration consistently ship pages that have never passed legal review. The approval topology \u2014 who approves, in what order, with what SLA, with what escalation path \u2014 must be modelled as a swimlane diagram before the first workflow is configured in the CMS. Retrofitting approval gates after a compliance incident means touching live workflow definitions, retraining authors mid-project, and auditing every piece of content published in the gap. Design the topology first; wire it second.</p></div>",
  "callout-before-after": "<div class=\"callout callout-before-after\"><span class=\"callout-label\">Before / After</span><div class=\"ba-grid\"><div><div class=\"ba-col-label\">Before</div><p>Analytics implemented post-launch, retrofitted via GTM, data layer undocumented, report rebuilt after every redesign.</p></div><div><div class=\"ba-col-label\">After</div><p>Data layer contract defined in Sprint 1, JSON Schema validated in CI, analytics team co-authors the schema, dashboards survive the redesign.</p></div></div></div>",
  "cards": "<div class=\"cards\">\n            <div class=\"cell\"><div class=\"ct\">For humans</div><h5>IA sitemap</h5><p>The conceptual site structure \u2014 page types, hierarchy, navigation. Drives the content model: what types exist, what attributes each carries.</p></div>\n            <div class=\"cell\"><div class=\"ct\">For search</div><h5>XML sitemap</h5><p>The file submitted to search engines for crawling. Auto-generated from the live site; updated as pages are added or retired.</p></div>\n          </div>",
  "versus": "<div class=\"versus\">\n            <div class=\"col\">\n              <div class=\"vt\">SEO \u00b7 Search Engine Optimization</div>\n              <p>The established discipline \u2014 rankings on Google, Bing, etc. Three pillars:</p>\n              <ul class=\"notes\" style=\"margin-top:6px\">\n                <li><b>Technical SEO</b> \u2014 sitemaps, structured data, performance, mobile, crawlability.</li>\n                <li><b>Content SEO</b> \u2014 keyword strategy, topical authority, depth.</li>\n                <li><b>Off-page SEO</b> \u2014 backlinks, mentions, domain authority.</li>\n              </ul>\n            </div>\n            <div class=\"col good\">\n              <div class=\"vt\">GEO \u00b7 Generative Engine Optimization</div>\n              <p>The new discipline \u2014 optimising for AI answer engines (ChatGPT, Perplexity, Claude, Google AI Overviews). Focus shifts:</p>\n              <ul class=\"notes\" style=\"margin-top:6px\">\n                <li><b>From \"rank\" to \"be cited\"</b> \u2014 appear in the AI's answer, with a source link back.</li>\n                <li><b>Levers</b> \u2014 structured content with clear claims, source links, freshness signals, schema markup, brand mentions across the web.</li>\n                <li><b>Maturity</b> \u2014 no playbook is fully proven yet. Frame as experiments, not commitments.</li>\n              </ul>\n            </div>\n          </div>",
  "arch-review": "<div class=\"arch-review\">\n            <div class=\"arch-label\">Architect's Review \u00b7 Content</div>\n            <ul>\n              <li>Is there a defined content model, and does every type fit it?</li>\n              <li>Is the IA sitemap maintained alongside the design system?</li>\n              <li>Is the source documented for every content type \u2014 including who provides and how?</li>\n              <li>Is the approval workflow named (people, SLAs, escalation) \u2014 not just understood?</li>\n              <li>Are tags and metadata enforced at upload, or applied retroactively?</li>\n              <li>Are asset expiries tracked, and what happens at expiry?</li>\n              <li>What is the current content velocity per type, and where's the bottleneck?</li>\n              <li>Where is AI assisting today, and where will it next?</li>\n            </ul>\n          </div>",
  "chips": "<div class=\"chips\"><span>Content Inventory</span><span>Content Model</span><span>Taxonomy</span><span>Metadata Framework</span><span>Localization Plan</span><span>Authoring Workflows</span><span>Governance Matrix</span><span>SEO Framework</span></div>",
  "code-ex": "<pre class=\"code-ex\"><span class=\"cm\">// The data layer is set once, per page, before any tags fire.</span>\nwindow.dataLayer = {\n  <span class=\"kw\">page</span>: {\n    name:     <span class=\"str\">\"Product Detail\"</span>,\n    category: <span class=\"str\">\"Electronics\"</span>,\n    language: <span class=\"str\">\"en-IN\"</span>\n  },\n  <span class=\"kw\">product</span>: {\n    sku:      <span class=\"str\">\"ABC123\"</span>,\n    name:     <span class=\"str\">\"Wireless Headphones\"</span>,\n    price:    <span class=\"val\">4999</span>,\n    currency: <span class=\"str\">\"INR\"</span>\n  },\n  <span class=\"kw\">user</span>: {\n    type:        <span class=\"str\">\"registered\"</span>,\n    loyaltyTier: <span class=\"str\">\"gold\"</span>\n  }\n};\n\n<span class=\"cm\">// When something happens, push an event.</span>\nwindow.dataLayer.push({\n  event:   <span class=\"str\">\"product:view\"</span>,\n  product: { sku: <span class=\"str\">\"ABC123\"</span> }\n});</pre>",
  "blockquote": "<blockquote>High content velocity is a competitive advantage. The brand that can ship a relevant campaign on a Friday afternoon will out-execute the brand that needs three weeks of approvals \u2014 regardless of which has the prettier creative.</blockquote>",
  "h4": "<h4>1 \u00b7 Localization workflows</h4>",
  "lead": "<p class=\"lead\">You never really write \"code.\" You answer one of a handful of questions, and each answer has a natural home. Memorise this map and you'll always know <em>where</em> a thing belongs before you write it.</p>"
};
